import { coresLog } from "../../constants/coresLog.constant.js";
import db from "../../models/db.model.js";
import CompetidorRepository from "../../repositories/competidor.repository.js";
import ConcursoRepository from "../../repositories/concurso.repository.js";
import cadastroParticipanteService from "../../services/cadastroParticipante.service.js";
import concursoService from "../../services/concurso.service.js";
import eventoService from "../../services/evento.service.js";
import consoleError from '../../utils/consoleError.util.js';

const competidorSeeder = async () => {
    console.log(`${coresLog.FgYellow}Criando fake data...${coresLog.Reset}`);
    try {
        const evento = {
            event_nome: "Campinas Anime Fest",
            event_local: "Liceu Salesiano",
            event_edicao: 30,
            event_cidade: 3509502,
            event_data: "10/12/2023"
        }
        await eventoService.criar(evento);

        const Concurso = new ConcursoRepository(db.concurso);
        const concursos = [];

        for (let i = 1; i <= 5; i++) {
            const concurso = await Concurso.buscarPorId(i);
            await concursoService.atualizar(i, {
                "conc_limit_inscr": 10,
                "conc_limit_espera": 10,
                "conc_limit_checkin": 10,
                "conc_ativo": true,
                "conc_data_ativ": "2023-12-01"
            });
            concursos.push({
                conc_id: concurso.conc_id,
                conc_nome: concurso.conc_nome,
            });
        }

        for (const inscricao of dados) {
            const competidor = criaCompetidor(
                inscricao.comp_email,
                inscricao.comp_nome,
                inscricao.comp_nome_social,
                inscricao.comp_cpf,
                inscricao.comp_nasc,
                inscricao.comp_whats,
                inscricao.comp_cidade
            );
            const apresentacao = criaApresentacao(
                inscricao.apres_nome,
                inscricao.apres_origem,
                inscricao.apres_link_ref
            );
            const participacao = criaParticipacao(
                concursos.find((element) => element.conc_nome === inscricao.part_conc_nome).conc_id,
                inscricao.part_event,
                inscricao.part_checkin,
                inscricao.part_tipo_inscr
            );
            const extra = criaExtra(
                inscricao.extra_integ,
                inscricao.extra_estil,
                inscricao.extra_link_av,
                inscricao.extra_categ,
                inscricao.extra_mat,
                inscricao.extra_mod
            );

            await cadastroParticipanteService.criar(
                competidor,
                apresentacao,
                participacao,
                extra,
                false
            );

            const Competidor = new CompetidorRepository(db.competidor);
            const competidorCadastrado = await Competidor.buscarPorCpf(inscricao.comp_cpf);
            await Competidor.atualizarPorId(competidorCadastrado.comp_id, { comp_email_verif: true });
            process.stdout.write('█');
        }
    } catch (error) {
        consoleError(error);
        throw error;
    }
    console.log();
    console.log(`${coresLog.FgGreen}Fake data criada!${coresLog.Reset}`);
}

const criaCompetidor = (email, nome, nomeSocial, cpf, dataNasc, whats, cidade) => {
    return {
        comp_email: email,
        comp_nome: nome,
        comp_nome_social: nomeSocial,
        comp_cpf: cpf,
        comp_nasc: dataNasc,
        comp_whats: whats,
        comp_cidade: cidade,
        comp_email_verif: true,
    };
};

const criaApresentacao = (nome, origem, linkRef) => {
    return {
        apres_nome: nome,
        apres_origem: origem,
        apres_link_ref: linkRef,
    };
};

const criaParticipacao = (concurso, evento, checkin, tipoInscr) => {
    return {
        part_conc: concurso,
        part_event: evento,
        part_aceit_regul: true,
        part_checkin: checkin,
        part_tipo_inscr: tipoInscr,
    };
};

const criaExtra = (integrantes, estilo, linkAv, categoria, material, modalidade) => {
    const extra = {};
    if (integrantes) extra.extra_integ = integrantes;
    if (estilo) extra.extra_estil = estilo;
    if (linkAv) extra.extra_link_av = linkAv;
    if (categoria) extra.extra_categ = categoria;
    if (material) extra.extra_mat = material;
    if (modalidade) extra.extra_mod = modalidade;
    return (Object.keys(extra).length === 0 && extra.constructor === Object) ? null : extra;
}

const dados = [
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Jonas Simão Brito de Amorim",
        "comp_whats": "19993258146",
        "comp_nome_social": "Alcide",
        "comp_cpf": "74749449016",
        "comp_nasc": "27/05/2000",
        "comp_email": "jonas.simao.bri@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 1,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Irene Karina de Burgos",
        "comp_whats": "19998608141",
        "comp_nome_social": "",
        "comp_cpf": "20611019760",
        "comp_nasc": "24/06/1997",
        "comp_email": "irene.karina.de@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Jorge Carrara de Cabral",
        "comp_whats": "19992179781",
        "comp_nome_social": "Aldoney",
        "comp_cpf": "07757200890",
        "comp_nasc": "29/01/1996",
        "comp_email": "jorge.carrara.d@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Aécio Eustáquio Casanova Maldonado de Coelho",
        "comp_whats": "19997359399",
        "comp_nome_social": "",
        "comp_cpf": "49515562511",
        "comp_nasc": "01/05/2001",
        "comp_email": "aecio.eustaquio@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Aécio",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Circuito",
        "comp_nome": "Danilo Estevão Carmona de Franco",
        "comp_whats": "19994124973",
        "comp_nome_social": "",
        "comp_cpf": "96879726020",
        "comp_nasc": "13/12/1998",
        "comp_email": "danilo.estevao@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Danilo",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "Não sei o que vai aqui",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Albino Flores de Garcia",
        "comp_whats": "19996339418",
        "comp_nome_social": "",
        "comp_cpf": "90966845161",
        "comp_nasc": "10/10/2000",
        "comp_email": "albino.flores.d@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 4,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Marlene Suely Casanova de Romero",
        "comp_whats": "19990217340",
        "comp_nome_social": "",
        "comp_cpf": "62837759260",
        "comp_nasc": "10/01/1994",
        "comp_email": "marlene.suely.c@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Marlene",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Circuito",
        "comp_nome": "Miranda Galvão de Romero",
        "comp_whats": "19992238356",
        "comp_nome_social": "",
        "comp_cpf": "64723778209",
        "comp_nasc": "11/05/1998",
        "comp_email": "miranda.galvao@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Miranda",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "Não sei o que vai aqui",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Marcos Ferraz de Gonçalves",
        "comp_whats": "19990995910",
        "comp_nome_social": "",
        "comp_cpf": "38535738274",
        "comp_nasc": "08/08/1994",
        "comp_email": "marcos.ferraz.d@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Circuito",
        "comp_nome": "Miguel Valentin Aranda de Junqueira",
        "comp_whats": "19996934339",
        "comp_nome_social": "",
        "comp_cpf": "51425266940",
        "comp_nasc": "26/04/1994",
        "comp_email": "miguel.valentin@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Miguel",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "Não sei o que vai aqui",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Emanuel Arnaldo Rezende de Sepúlveda",
        "comp_whats": "19991031623",
        "comp_nome_social": "",
        "comp_cpf": "55551478564",
        "comp_nasc": "12/07/1997",
        "comp_email": "emanuel.arnaldo@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Ademar Reginaldo Batista Dominato",
        "comp_whats": "19993008046",
        "comp_nome_social": "",
        "comp_cpf": "16574515181",
        "comp_nasc": "14/06/1991",
        "comp_email": "ademar.reginald@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 2,
        "extra_integ": "Ademar",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Antonieta Margarete Colaço Cortês",
        "comp_whats": "19998924064",
        "comp_nome_social": "",
        "comp_cpf": "56321291366",
        "comp_nasc": "02/11/1992",
        "comp_email": "antonieta.marga@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 2,
        "extra_integ": "Antonieta",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Jack Roberval Mascarenhas Ramires",
        "comp_whats": "19999083504",
        "comp_nome_social": "",
        "comp_cpf": "52104184991",
        "comp_nasc": "12/11/1994",
        "comp_email": "jack.roberval.m@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Jack",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Dário Emanoel Correia Mascarenhas",
        "comp_whats": "19992915538",
        "comp_nome_social": "Aercio",
        "comp_cpf": "36007004805",
        "comp_nasc": "16/03/1998",
        "comp_email": "dario.emanoel.c@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Dário",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Diogo Chaves Mascarenhas",
        "comp_whats": "19995077155",
        "comp_nome_social": "",
        "comp_cpf": "55669277260",
        "comp_nasc": "30/01/1993",
        "comp_email": "diogo.chaves.ma@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Diogo",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 2
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Marco Mário Molina de Álvares",
        "comp_whats": "19991615027",
        "comp_nome_social": "",
        "comp_cpf": "59620657861",
        "comp_nasc": "14/04/1996",
        "comp_email": "marco.mario.mol@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 2,
        "extra_integ": "Marco",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Barnabé Otávio Bezerra de Bezerra",
        "comp_whats": "19998182167",
        "comp_nome_social": "",
        "comp_cpf": "14705264843",
        "comp_nasc": "04/05/1994",
        "comp_email": "barnabe.otavio@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Barnabé",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 1
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Inácio Nicolas de Delgado",
        "comp_whats": "19992432440",
        "comp_nome_social": "Aliciano",
        "comp_cpf": "76871643184",
        "comp_nasc": "09/10/1999",
        "comp_email": "inacio.nicolas@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Inácio",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 2
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Anderson Caio Gusmão Neves de Espanha",
        "comp_whats": "19992511750",
        "comp_nome_social": "",
        "comp_cpf": "18687671911",
        "comp_nasc": "12/04/1991",
        "comp_email": "anderson.caio.g@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 5,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Michele Espinoza de Fonseca",
        "comp_whats": "19994906721",
        "comp_nome_social": "Advalter",
        "comp_cpf": "06549802687",
        "comp_nasc": "05/07/1990",
        "comp_email": "michele.espinoz@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 6,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Albina Heloísa Galvão de Madeira",
        "comp_whats": "19998286691",
        "comp_nome_social": "Aladilson",
        "comp_cpf": "31897436572",
        "comp_nasc": "19/11/1989",
        "comp_email": "albina.heloisa@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Albina",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 2
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Emília Cordeiro de Madeira",
        "comp_whats": "19991467234",
        "comp_nome_social": "Alberte",
        "comp_cpf": "73115841248",
        "comp_nasc": "29/07/1996",
        "comp_email": "emilia.cordeiro@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Emília",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Manuela Estrada de Marques",
        "comp_whats": "19993824687",
        "comp_nome_social": "",
        "comp_cpf": "95141084426",
        "comp_nasc": "26/02/1995",
        "comp_email": "manuela.estrada@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 3,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Mayara Telma Lozano de Menezes",
        "comp_whats": "19994736693",
        "comp_nome_social": "Agadir",
        "comp_cpf": "90866697608",
        "comp_nasc": "29/12/1991",
        "comp_email": "mayara.telma.lo@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Mayara",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 1
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Bianca Amanda Benites de Pereira",
        "comp_whats": "19998159711",
        "comp_nome_social": "Alailtom",
        "comp_cpf": "85055243490",
        "comp_nasc": "31/05/1991",
        "comp_email": "bianca.amanda.b@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Circuito",
        "comp_nome": "Isadora Prado",
        "comp_whats": "19996261884",
        "comp_nome_social": "",
        "comp_cpf": "55200750180",
        "comp_nasc": "08/07/1996",
        "comp_email": "isadora.prado@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Isadora",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "Não sei o que vai aqui",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Edson Jonathan Rezende de Roque",
        "comp_whats": "19993620973",
        "comp_nome_social": "",
        "comp_cpf": "97109053768",
        "comp_nasc": "02/05/1994",
        "comp_email": "edson.jonathan@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 3,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Fabíola Suely Caldeira de Figueira",
        "comp_whats": "19992833091",
        "comp_nome_social": "Adjuto",
        "comp_cpf": "98537630799",
        "comp_nasc": "14/11/1989",
        "comp_email": "fabiola.suely.c@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Milton Nathan de Gil Neto",
        "comp_whats": "19991191984",
        "comp_nome_social": "",
        "comp_cpf": "07085636866",
        "comp_nasc": "27/12/1990",
        "comp_email": "milton.nathan.d@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Milton",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 1
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Miranda Carrara de Iglesias",
        "comp_whats": "19991747161",
        "comp_nome_social": "Advando",
        "comp_cpf": "37860083531",
        "comp_nasc": "04/04/1991",
        "comp_email": "miranda.carrara@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Jesus Samuel de Martines",
        "comp_whats": "19995348870",
        "comp_nome_social": "",
        "comp_cpf": "57013604070",
        "comp_nasc": "23/03/1998",
        "comp_email": "jesus.samuel.de@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Jesus",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Manuel Cleberson Azevedo Chaves",
        "comp_whats": "19993397666",
        "comp_nome_social": "",
        "comp_cpf": "19323433349",
        "comp_nasc": "24/09/1992",
        "comp_email": "manuel.cleberso@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 5,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Raí Sérgio Oliveira Prado",
        "comp_whats": "19995717403",
        "comp_nome_social": "",
        "comp_cpf": "96731107433",
        "comp_nasc": "15/07/1998",
        "comp_email": "rai.sergio.oliv@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Raí",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Gisele Barros",
        "comp_whats": "19999102441",
        "comp_nome_social": "Almim",
        "comp_cpf": "42354216114",
        "comp_nasc": "13/08/1990",
        "comp_email": "gisele.barros@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 2,
        "extra_integ": "Gisele",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Andressa Godói",
        "comp_whats": "19991765591",
        "comp_nome_social": "",
        "comp_cpf": "50926802615",
        "comp_nasc": "11/05/1992",
        "comp_email": "andressa.godoi@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Andressa",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 1
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Damião Gilson Gil",
        "comp_whats": "19994549710",
        "comp_nome_social": "",
        "comp_cpf": "56906185438",
        "comp_nasc": "21/03/1992",
        "comp_email": "damiao.gilson.g@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 5,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Circuito",
        "comp_nome": "Júlia Bruna Correia Delvalle de Melo",
        "comp_whats": "19992310861",
        "comp_nome_social": "",
        "comp_cpf": "83995402852",
        "comp_nasc": "28/11/1993",
        "comp_email": "julia.bruna.cor@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Júlia",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "Não sei o que vai aqui",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Hilda Delvalle Pacheco",
        "comp_whats": "19990609968",
        "comp_nome_social": "",
        "comp_cpf": "47445191305",
        "comp_nasc": "10/11/1993",
        "comp_email": "hilda.delvalle@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Ivanete Sílvia Faria",
        "comp_whats": "19998507150",
        "comp_nome_social": "Alequesandro",
        "comp_cpf": "63741246506",
        "comp_nasc": "21/12/1990",
        "comp_email": "ivanete.silvia@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Ivanete",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Michele Bruna Benites",
        "comp_whats": "19990329432",
        "comp_nome_social": "",
        "comp_cpf": "72974538460",
        "comp_nasc": "01/07/1990",
        "comp_email": "michele.bruna.b@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 2,
        "extra_integ": "Michele",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Circuito",
        "comp_nome": "Andres Aragão de Ortiz",
        "comp_whats": "19996533163",
        "comp_nome_social": "",
        "comp_cpf": "01027935141",
        "comp_nasc": "28/05/1993",
        "comp_email": "andres.aragao.d@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Andres",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "Não sei o que vai aqui",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Diogo Rocha Filho",
        "comp_whats": "19996258550",
        "comp_nome_social": "Admauro",
        "comp_cpf": "79828037769",
        "comp_nasc": "18/08/1991",
        "comp_email": "diogo.rocha.fil@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 5,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Ederson Burgos Camacho",
        "comp_whats": "19990489298",
        "comp_nome_social": "",
        "comp_cpf": "69595822612",
        "comp_nasc": "12/05/1994",
        "comp_email": "ederson.burgos@jhowcass.net",
        "comp_cidade": 3501608,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Ederson",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 1
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Karaoke",
        "comp_nome": "Noel Everton Aguiar de Faria",
        "comp_whats": "19998907722",
        "comp_nome_social": "",
        "comp_cpf": "12224969333",
        "comp_nasc": "12/04/1995",
        "comp_email": "noel.everton.ag@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Circuito",
        "comp_nome": "Heitor Paz Reis",
        "comp_whats": "19997619797",
        "comp_nome_social": "",
        "comp_cpf": "30251639410",
        "comp_nasc": "06/12/1998",
        "comp_email": "heitor.paz.reis@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": 1,
        "extra_integ": "Heitor",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Camilo Estrada Duque",
        "comp_whats": "19990218400",
        "comp_nome_social": "",
        "comp_cpf": "00488446678",
        "comp_nasc": "05/04/1990",
        "comp_email": "camilo.estrada@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Camilo",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 2
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Kpop Solo / Duo",
        "comp_nome": "Joaquin Lucas Flores de Gil",
        "comp_whats": "19994231026",
        "comp_nome_social": "",
        "comp_cpf": "45810660509",
        "comp_nasc": "25/10/2001",
        "comp_email": "joaquin.lucas.f@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": "",
        "extra_estil": "",
        "extra_integ": "Joaquin",
        "extra_link_av": "https://www.youtube.com/watch?v=L0_nXyTMyqM",
        "extra_mat": "",
        "extra_mod": 2
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Josué Balestero Neto",
        "comp_whats": "19994548020",
        "comp_nome_social": "",
        "comp_cpf": "90947524843",
        "comp_nasc": "05/08/1989",
        "comp_email": "josue.balestero@jhowcass.net",
        "comp_cidade": 3509502,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 1,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    },
    {
        "part_event": 1,
        "part_conc": 0,
        "part_conc_nome": "Cosplay Desfile",
        "comp_nome": "Oliver Paulo Chaves",
        "comp_whats": "19998930080",
        "comp_nome_social": "",
        "comp_cpf": "54950824864",
        "comp_nasc": "18/07/1994",
        "comp_email": "oliver.paulo.ch@jhowcass.net",
        "comp_cidade": 3533403,
        "apres_nome": "Goku",
        "apres_origem": "Dragon Ball Z",
        "apres_link_ref": "https://static.wikia.nocookie.net/tkoc/images/0/09/Goku.png/revision/latest?cb=20130424212620&path-prefix=pt-br",
        "extra_categ": 4,
        "extra_estil": "",
        "extra_integ": "",
        "extra_link_av": "",
        "extra_mat": "",
        "extra_mod": ""
    }
];

export default competidorSeeder;